env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier:
    - error
    -
      singleQuote: true
      trailingComma: 'es5'
  no-console: off
  eqeqeq: error
  no-var: error
  prefer-const: error
  no-unused-vars: warn
  no-control-regex: warn
  no-empty:
    - warn
    -
      allowEmptyCatch: true
